### ISSUE TITLE
Extension does not insert anything in text editor

### ISSUE THREAD

**Issue by lgaborini** [mblode/vscode-zotero#4]
I hit the key combination, the citation selector appears (often in the background).  
I select the chosen citation, the selector disappears but nothing happens in the Editor.

Here is the error log:
```
[2019-08-15 18:51:34.592] [renderer1] [error] TextEditor#edit not possible on closed editors: Error: TextEditor#edit not possible on closed editors
	at f.edit (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:484:129)
	at C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\extension.js:11:12
	at tryCatcher (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\util.js:16:23)
	at Promise.module.exports.Promise._settlePromiseFromHandler (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\promise.js:517:31)
	at Promise.module.exports.Promise._settlePromise (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\promise.js:574:18)
	at Promise.module.exports.Promise._settlePromise0 (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\promise.js:619:10)
	at Promise.module.exports.Promise._settlePromises (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\promise.js:699:18)
	at _drainQueueStep (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\async.js:138:12)
	at _drainQueue (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\async.js:131:9)
	at Async._drainQueues (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\async.js:147:5)
	at Immediate.Async.drainQueues (C:\Users\Lorenzo\.vscode\extensions\mblode.zotero-0.1.8\node_modules\bluebird\js\release\async.js:17:14)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
```

Extension version: 0.1.8
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18895

**Comment by wiheto** [comment]
I get the same problem. Any solution to this?

Extension version: 0.1.9

VS Code info: 

Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-13T14:40:29.529Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic snap

**Comment by lgaborini** [comment]
0.1.9 works for me, although the selector still appears in the background.  

Extension version: 0.1.9
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

**Comment by samuelsaari** [comment]
This happens to me periodically. Once it does it won't insert anything anymore.
0.1.9.
Win10 64 bit
VScode 1.44.2

**Comment by AshtonSBradley** [comment]
same problem on macos, extension version 0.1.9

VScode info:

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by Hocnonsense** [comment]
same problem on windows, version 0.1.9
When I open a new vscode, open a `.md` file, hit the key combination and choose a citation, the text will insert as well.
I can add a number of citation in the same file.
Howver, **once** I go to a *new* file, it won't insert **anything** anymore.


version: 1.48.2 (user setup)
commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
